# https://esphome.io/components/sensor/ld2410.html

ld2410:
  - id: "${id}"
    throttle: "${throttle}"
    uart_id: "${uart_id}"

number:
  - platform: ld2410
    ld2410_id: "${id}"
    timeout:
      name: "${name} Timeout"
    light_threshold:
      name: "${name} Light Threshold"
    max_move_distance_gate:
      name: "${name} Max Move Distance Gate"
    max_still_distance_gate:
      name: "${name} Max Still Distance Gate"
    g0:
      move_threshold:
        name: "${name} g0 move threshold"
      still_threshold:
        name: "${name} g0 still threshold"
    g1:
      move_threshold:
        name: "${name} g1 move threshold"
      still_threshold:
        name: "${name} g1 still threshold"
    g2:
      move_threshold:
        name: "${name} g2 move threshold"
      still_threshold:
        name: "${name} g2 still threshold"
    g3:
      move_threshold:
        name: "${name} g3 move threshold"
      still_threshold:
        name: "${name} g3 still threshold"
    g4:
      move_threshold:
        name: "${name} g4 move threshold"
      still_threshold:
        name: "${name} g4 still threshold"
    g5:
      move_threshold:
        name: "${name} g5 move threshold"
      still_threshold:
        name: "${name} g5 still threshold"
    g6:
      move_threshold:
        name: "${name} g6 move threshold"
      still_threshold:
        name: "${name} g6 still threshold"
    g7:
      move_threshold:
        name: "${name} g7 move threshold"
      still_threshold:
        name: "${name} g7 still threshold"
    g8:
      move_threshold:
        name: "${name} g8 move threshold"
      still_threshold:
        name: "${name} g8 still threshold"

binary_sensor:
  - platform: ld2410
    ld2410_id: "${id}"
    has_target:
      name: "${name}"
      id: motion_mmwave
    has_moving_target:
      name: "${name} Moving Target"
    has_still_target:
      name: "${name} Still Target"
    out_pin_presence_status:
      name: "${name} out pin presence status"

sensor:
  - platform: ld2410
    ld2410_id: "${id}"
    light:
      name: light
    moving_distance:
      name: "${name} Moving Distance"
    still_distance:
      name: "${name} Still Distance"
    moving_energy:
      name: "${name} Move Energy"
    still_energy:
      name: "${name} Still Energy"
    detection_distance:
      name: "${name} Detection Distance"
    g0:
      move_energy:
        name: "${name} g0 move energy"
      still_energy:
        name: "${name} g0 still energy"
    g1:
      move_energy:
        name: "${name} g1 move energy"
      still_energy:
        name: "${name} g1 still energy"
    g2:
      move_energy:
        name: "${name} g2 move energy"
      still_energy:
        name: "${name} g2 still energy"
    g3:
      move_energy:
        name: "${name} g3 move energy"
      still_energy:
        name: "${name} g3 still energy"
    g4:
      move_energy:
        name: "${name} g4 move energy"
      still_energy:
        name: "${name} g4 still energy"
    g5:
      move_energy:
        name: "${name} g5 move energy"
      still_energy:
        name: "${name} g5 still energy"
    g6:
      move_energy:
        name: "${name} g6 move energy"
      still_energy:
        name: "${name} g6 still energy"
    g7:
      move_energy:
        name: "${name} g7 move energy"
      still_energy:
        name: "${name} g7 still energy"
    g8:
      move_energy:
        name: "${name} g8 move energy"
      still_energy:
        name: "${name} g8 still energy"

switch:
  - platform: ld2410
    ld2410_id: "${id}"
    engineering_mode:
      name: "${name} Engineering Mode"
    bluetooth:
      name: "${name} Bluetooth"

button:
  - platform: ld2410
    ld2410_id: "${id}"
    factory_reset:
      name: "${name} Factory Reset"
    restart:
      name: "${name} Restart"
    query_params:
      name: "${name} Force Refresh"

text_sensor:
  - platform: ld2410
    ld2410_id: "${id}"
    version:
      name: "${name} Firmware Version"
    mac_address:
      name: "${name} Mac Address"

select:
  - platform: ld2410
    ld2410_id: "${id}"
    distance_resolution:
      name: "${name} Distance Resolution"
    baud_rate:
      name: "${name} Baud Rate"
    light_function:
      name: "${name} Light Function"
    out_pin_level:
      name: "${name} Out Pin Level"
